manifest:
  remotes:
    - name: nickconway
      url-base: https://github.com/nickconway
    - name: m165437
      url-base: https://github.com/M165437
  projects:
    - name: zmk
      remote: nickconway
      revision: dev
      import: app/west.yml
    - name: nice-view-gem
      remote: m165437
      revision: main
      path: extra-modules/nice-view-gem
  self:
    path: config
